swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - https
host: simple.api
basePath: /openapi101

paths:
  /persons:
    get:
      summary: résumé
      description: description trèèèès longue quoi
      parameters:
        - name: age
          in: query
          type: integer
          description: coucou
      responses:
        200:
          description: Tout va bien
          schema:
            $ref: "person.yml#/Persons"
        400:
          $ref: "#/responses/Error400"

  /persons/{username}:
    parameters:
      - $ref: "#/parameters/username"
    get:
      description: récupérer qqn
      responses:
        200:
          description: Voici le username
          schema:
            $ref: "person.yml#/Person"
        500:
          $ref: "#/responses/Error500"

definitions:
  Error400:
    properties:
      message:
        type: string

parameters:
  username:
    name: username
    in: path
    required: true
    type: string
    pattern: "[a-z0-9]{8,64}"

responses:
  Error400:
    description: Une erreur est survenue
    schema:
      $ref: "#/definitions/Error400"