swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - https
host: simple.api
basePath: /openapi101

paths:
  /persons:
    get:
      summary: résumé
      description: description trèèèès longue quoi
      parameters:
        - name: age
          in: query
          type: integer
          description: coucou
      responses:
        200:
          description: Tout va bien
          schema:
            $ref: "#/definitions/Persons"
        400:
          $ref: "#/responses/Error400"

definitions:
  Person:
    required:
      - username
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
      age:
        type: integer

  Persons:
    type: array
    items:
      $ref: "#/definitions/Person"

  Error400:
    properties:
      message:
        type: string

responses:
  Error400:
    description: Une erreur est survenue
    schema:
      $ref: "#/definitions/Error400"